/// Flutter icons Unicons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Unicons
///      fonts:
///       - asset: fonts/Unicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Unicons {
  Unicons._();

  static const String _kFontFam = 'Unicons';

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dice_multiple = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ban = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData favourite = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe806, fontFamily: _kFontFam);
}
