include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - conditional_uri_does_not_exist
    - directives_ordering
    - literal_only_boolean_expressions
    - prefer_asserts_with_message
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - throw_in_finally
    - unnecessary_await_in_return
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_colored_box
    - use_decorated_box
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
analyzer:
  exclude:
    - fvm/
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/config/env.dart
    - lib/generated_plugin_registrant.dart
    - test/**/*.mocks.dart
