// ignore_for_file: member-ordering
/// Flutter icons Unicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const String _kFontFam = 'CustomIcons';

  static const IconData diceMultiple = IconData(0xe800, fontFamily: _kFontFam);
}
