name: Build and test
on:
  push:

  pull_request:
    branches: [main]

# This ensures that previous jobs for the PR are canceled when PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Get repository
      uses: actions/checkout@v4
    - name: Configure enviroment
      env:
        ENV_PROD_BASE64: ${{ secrets.ENV_PROD_BASE64 }}
        ENV_DEV_BASE64: ${{ secrets.ENV_DEV_BASE64 }}
      run: |
        echo $ENV_PROD_BASE64 | base64 -di > .env/prod.json
        echo $ENV_DEV_BASE64 | base64 -di > .env/dev.json
    - name: Setup Flutter
      uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      with:
        path: '.fvmrc'
    - name: Install dependencies
      run: sh tool/setup.sh
    - name: Verify formatted files
      run: |
        dart format $(find . -type f -name "*.dart" \
          ! -path "**/*.g.dart" \
          ! -path "**/*.mocks.dart" \
          ! -path "**/*.config.dart") --set-exit-if-changed
    - name: Analyze code
      run: flutter analyze
    - name: Test
      run: sh tool/unit-test.sh prod